#!/usr/bin/env python3
"""Measure the corpus: size, and how much of it is actually there.

For each scroll, counts words and classifies them as extant, reconstructed
(inside [ ]), or uncertain (carrying a dot-above or circle). Emits a Markdown
table so the numbers are diffable in git - a change in the reconstruction ratio
shows up in a pull request the same way a code change would.

Usage:
    python3 corpus_stats.py [--src DIR] [--out FILE] [--json FILE]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

LINE_RE = re.compile(r"^(?P<siglum>\S+) (?P<column>[^:\s]+):(?P<line>\S+)(?:\s+(?P<content>.*))?$")
DOT_ABOVE, CIRCLE, UNREADABLE = "̇", "֯", "◌"
MARKUP = set("[](){}〚〛^<>-.?!+0123456789  ⸱")


def measure(path: str) -> dict:
    words = extant = reconstructed = uncertain = 0
    gaps = lines = 0
    columns: set[str] = set()

    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            m = LINE_RE.match(raw.rstrip("\n"))
            if not m:
                continue
            lines += 1
            columns.add(m.group("column"))
            content = m.group("content") or ""
            gaps += content.count("--")

            depth = 0
            token = ""
            token_bracketed = False
            for ch in content + " ":
                if ch == "[":
                    depth += 1
                    continue
                if ch == "]":
                    depth = max(0, depth - 1)
                    continue
                if ch in "  ":
                    if token:
                        words += 1
                        if token_bracketed:
                            reconstructed += 1
                        else:
                            extant += 1
                        if DOT_ABOVE in token or CIRCLE in token:
                            uncertain += 1
                    token = ""
                    token_bracketed = False
                    continue
                if ch in MARKUP or ch == UNREADABLE:
                    continue
                token += ch
                if depth > 0:
                    token_bracketed = True

    return {
        "lines": lines, "columns": len(columns), "words": words,
        "extant": extant, "reconstructed": reconstructed,
        "uncertain": uncertain, "gaps": gaps,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="original/scroll")
    ap.add_argument("--out", default="STATS.md")
    ap.add_argument("--json", default="derived/corpus-stats.json")
    args = ap.parse_args()

    if not os.path.isdir(args.src):
        print(f"error: no such directory: {args.src}", file=sys.stderr)
        return 2

    per_scroll = {}
    for name in sorted(os.listdir(args.src)):
        if name.endswith(".txt"):
            per_scroll[name[:-4]] = measure(os.path.join(args.src, name))

    total = {k: sum(s[k] for s in per_scroll.values())
             for k in ("lines", "columns", "words", "extant", "reconstructed",
                       "uncertain", "gaps")}

    def pct(a: int, b: int) -> str:
        return f"{100 * a / b:.1f}%" if b else "—"

    rows = sorted(per_scroll.items(), key=lambda kv: -kv[1]["words"])
    lines_md = [
        "# Corpus statistics",
        "",
        "Generated by `scripts/corpus_stats.py`. Do not edit by hand.",
        "",
        f"**{len(per_scroll)} scrolls · {total['lines']:,} lines · "
        f"{total['words']:,} words** — {pct(total['extant'], total['words'])} extant, "
        f"{pct(total['reconstructed'], total['words'])} reconstructed, "
        f"{pct(total['uncertain'], total['words'])} carrying a certainty mark, "
        f"{total['gaps']:,} lacunae.",
        "",
        "| Scroll | Cols | Lines | Words | Extant | Reconstructed | Uncertain | Gaps |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for siglum, s in rows:
        lines_md.append(
            f"| `{siglum}` | {s['columns']} | {s['lines']} | {s['words']} | "
            f"{pct(s['extant'], s['words'])} | {pct(s['reconstructed'], s['words'])} | "
            f"{pct(s['uncertain'], s['words'])} | {s['gaps']} |"
        )

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines_md) + "\n")

    os.makedirs(os.path.dirname(args.json) or ".", exist_ok=True)
    with open(args.json, "w", encoding="utf-8") as fh:
        json.dump({"total": total, "scrolls": per_scroll}, fh, indent=1, sort_keys=True)
        fh.write("\n")

    headline = (
        f"{len(per_scroll)} scrolls, {total['words']:,} words, "
        f"{pct(total['reconstructed'], total['words'])} reconstructed"
    )
    print(headline)

    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a", encoding="utf-8") as fh:
            fh.write(f"## Corpus statistics\n\n{headline}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
