name: Convert TXT to XML

on:
  push:
    paths:
      - "original/scroll/*.txt"  # Trigger when any .txt file in original/scroll changes

jobs:
  convert-txt-to-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get Modified File
        id: get-file
        run: |
          FILE=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^original/scroll/.*\.txt$' | head -n 1)
          if [[ -z "$FILE" ]]; then
            echo "No changed TXT file found."
            exit 1
          fi
          echo "Modified file: $FILE"
          echo "TXT_FILE=$FILE" >> $GITHUB_ENV
          echo "XML_FILE=${FILE%.txt}.xml" >> $GITHUB_ENV

      - name: Run Script to Convert TXT to XML
        run: |
          python3 scripts/txt_to_s_xml.py $TXT_FILE

      - name: Commit and Push XML File
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

          if [[ -f "$XML_FILE" ]]; then
            git add "$XML_FILE"
            git commit -m "Auto-converted $TXT_FILE to XML"
            git push
          else
            echo "No XML file generated, skipping commit."
          fi
        continue-on-error: true  # Prevent errors if no new changes exist
