name: Split DSS File

on:
  push:
    paths:
      - "dss.txt"  # Trigger workflow only when dss.txt changes

jobs:
  split-dss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Script to Split dss.txt
        run: |
          python3 -c "
import os

def split_file(input_file):
    input_dir = os.path.dirname(input_file)
    output_dir = os.path.join(input_dir, 'scroll')
    os.makedirs(output_dir, exist_ok=True)

    with open(input_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    current_file = None
    content = []

    for line in lines:
        if line.strip() == '':
            if current_file and content:
                with open(os.path.join(output_dir, current_file), 'w', encoding='utf-8') as out_f:
                    out_f.writelines(content)
                current_file = None
                content = []
        else:
            if current_file is None:
                current_file = f'{line.strip()}.txt'
            else:
                content.append(line)

    if current_file and content:
        with open(os.path.join(output_dir, current_file), 'w', encoding='utf-8') as out_f:
            out_f.writelines(content)

    print(f'Split completed. Output files are saved in the {output_dir} directory.')

split_file('dss.txt')
"

      - name: Commit and Push Output Files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          
          # Add only if changes exist
          if [[ -n $(git status --porcelain scroll/) ]]; then
            git add scroll/
            git commit -m 'Auto-split dss.txt into separate files'
            git push
          else
            echo "No changes detected in scroll/, skipping commit."
          fi
        continue-on-error: true  # Prevent errors if no changes are detected
